// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	storage "github.com/triumphpc/go-musthave-shortener-tpl/internal/app/storage"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// LinkBy provides a mock function with given fields: sl
func (_m *Repository) LinkBy(sl storage.ShortLink) (string, error) {
	ret := _m.Called(sl)

	var r0 string
	if rf, ok := ret.Get(0).(func(storage.ShortLink) string); ok {
		r0 = rf(sl)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(storage.ShortLink) error); ok {
		r1 = rf(sl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: url
func (_m *Repository) Save(url string) storage.ShortLink {
	ret := _m.Called(url)

	var r0 storage.ShortLink
	if rf, ok := ret.Get(0).(func(string) storage.ShortLink); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Get(0).(storage.ShortLink)
	}

	return r0
}
